version: '3'
services:
  caddy:
    image: abiosoft/caddy
    ports:
      - "2015:2015"
      - "80:80"
      - "443:443"
    volumes: 
      - ../api:/var/www
      - ./Caddyfile:/etc/Caddyfile
    environment:
      - ACME_AGREE=true
  php:
    image: php:7-fpm
    volumes:
      - ../api:/var/www
  # netdata:
  #   image: netdata/netdata
  #   ports:
  #     - "19999:19999"
  #   volumes:
  #   #   - /proc:/proc
  #   #   - /sys:/sys
  #     - /var/run/docker.sock:/var/run/docker.sock